config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence:
  true,
  length: {
     minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def index
    @articles = Article.all
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
end

def edit
  @article =
  Article.find(params[:id])
end
  def update
    @article = Article.find(params[:id])
    if @article.save
      redirect_to @article
    else
      render 'new'
    end

end

  def show
    @article = Article.find(params[:id])
  end



  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_index.html.erb
<h1>Put picture here</h1>
<%#= link_to 'Wynwalls',controller: 'articles' %>

<%= link_to 'New review',
new_article_path %>

<h1>List of Reviews</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Review</th>
    <th colspan="2"></th>
  </tr>

  <%= link_to 'Reviews',
  new_article_path %>

  <% @articles.each do |article| %>
    <tr>

      <td><%= article.title %>
      </td>
      <td><%= article.text %>
      </td>
      <!-- <td><%#= link_to 'Edit',
      edit_article_path(article) %></td> -->
    </tr>

</td>
        <% end %>
      </table>

app/views/articles/edit.html.erb
<h1>editing article</h1>

<%= form_for :article, url:
article_path(@article), method:
:patch do |f| %>

<% if @article.errors.any? %>

<div id="error_explanation">
  <h2><%=
  pluralize(@article.errors.count, "error") %> prohibited this
  article from being saved:</h2>
  <u1>
    <%
    @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>

    <% end %>
  </u1>
</div>
<% end %>
<p>
  <%= f.label :picture %><br>
  <%= f.text_field :text %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%#= link_to 'Wynwalls',controller: 'articles' %>

<%= link_to 'New review',
new_article_path %>

<h1>List of Reviews</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Review</th>
    <th colspan="2"></th>
  </tr>

  <%= link_to 'Reviews',
  new_article_path %>

  <% @articles.each do |article| %>
    <tr>

      <td><%= article.title %>
      </td>
      <td><%= article.text %>
      </td>
      <!-- <td><%#= link_to 'Edit',
      edit_article_path(article) %></td> -->
    </tr>

</td>
        <% end %>
      </table>

app/views/articles/new.html.erb
<h1> New Review </h1>

<%= form_for :article, url:articles_path do |f| %>

<p>
  <%= f.label :title, "Name" %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text, "Review" %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit "New Review" %>

</p>
<% end %>
<%= link_to 'Back', articles_path
%>

app/views/articles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Review:</strong>
  <%= @article.text %>
</p>



<%= link_to 'Back', articles_path %>
<%#= link_to 'Edit',
edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Wynwalls Landing Page</h1>

<!-- NOTE: this is the landing page map of Wynwood goes here-->